sudo: false
language: c

cache:
  directories:
    - .cabal-sandbox

matrix:
  include:
    - env: CABALVER=1.18 GHCVER=7.6.3
      addons: {apt: {sources: [hvr-ghc], packages: [cabal-install-1.18,ghc-7.6.3,happy-1.19.5,alex-3.1.4]}}
    - env: CABALVER=1.18 GHCVER=7.8.4
      addons: {apt: {sources: [hvr-ghc], packages: [cabal-install-1.18,ghc-7.8.4,happy-1.19.5,alex-3.1.4]}}
    - env: CABALVER=1.22 GHCVER=7.10.2
      addons: {apt: {sources: [hvr-ghc], packages: [cabal-install-1.22,ghc-7.10.2,happy-1.19.5,alex-3.1.4]}}
    - env: CABALVER=head GHCVER=head
      addons: {apt: {sources: [hvr-ghc], packages: [cabal-install-head,ghc-head,happy-1.19.5,alex-3.1.4]}}

  allow_failures:
    - env: CABALVER=head GHCVER=head

before_install:
  - env
  - git clone https://github.com/emilaxelsson/language-c-quote.git --branch no-haskell-src-meta
  - git clone https://github.com/emilaxelsson/imperative-edsl
  - git clone https://github.com/Feldspar/feldspar-language
  - git clone https://github.com/Feldspar/feldspar-compiler
  - git clone https://github.com/emwap/feldspar-compiler-shim
  - cd $TRAVIS_BUILD_DIR/imperative-edsl        && git fetch -v && git checkout $TRAVIS_BRANCH || git checkout master
  - cd $TRAVIS_BUILD_DIR/feldspar-language      && git fetch -v && git checkout $TRAVIS_BRANCH || git checkout master
  - cd $TRAVIS_BUILD_DIR/feldspar-compiler      && git fetch -v && git checkout $TRAVIS_BRANCH || git checkout master
  - cd $TRAVIS_BUILD_DIR/feldspar-compiler-shim && git fetch -v && git checkout $TRAVIS_BRANCH || git checkout master
  - cd $TRAVIS_BUILD_DIR
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
  - export PATH=/opt/alex/3.1.4/bin:/opt/happy/1.19.5/bin:$PATH

install:
  - cabal --version
  - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
  - travis_retry cabal update
  - cabal sandbox init
  - cabal sandbox add-source language-c-quote
  - cabal sandbox add-source imperative-edsl
  - cabal sandbox add-source feldspar-language
  - cabal sandbox add-source feldspar-compiler
  - cabal sandbox add-source feldspar-compiler-shim
  - cabal install -f-full-haskell-antiquotes language-c-quote
  - cabal install --only-dependencies --enable-tests --enable-benchmarks --force-reinstalls

script:
 - cabal configure --enable-tests --enable-benchmarks -v2
 - cabal build
 - cabal test
 - cabal check
 - cabal sdist
 - export SRC_TGZ=$(cabal info . | awk '{print $2;exit}');
   cd dist/;
   if [ -f "$SRC_TGZ".tar.gz ]; then
     cabal unpack "$SRC_TGZ".tar.gz;
     cd "$SRC_TGZ";
     cabal sandbox init --sandbox ../../.cabal-sandbox;
     cabal configure --disable-optimization --enable-test;
     cabal build;
     cabal install --disable-optimization --force-reinstalls;
   else
      echo "expected '$SRC_TGZ.tar.gz' not found";
      exit 1;
   fi

